# Docker image
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'terraform-azurerm-mariadb:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker run --rm $(imageName) bash -c "./test.sh validate"
  displayName: 'validate test'

- script: docker run -e "ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)" -e "ARM_CLIENT_ID=$(AZURE_CLIENT_ID)" -e "ARM_CLIENT_SECRET=$(AZURE_CLIENT_SECRET)" -e "ARM_TENANT_ID=$(AZURE_TENANT_ID)" --rm $(imageName) bash -c "./test.sh full"
  displayName: 'full test'